fix: Stop relocating caffeine (#8143)
I believe this is causing issues downstream in security

```
 Caused by: java.lang.NoClassDefFoundError: io/micronaut/caffeine/cache/Expiry
      at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
      ... 86 more
  Caused by: java.lang.ClassNotFoundException: io.micronaut.caffeine.cache.Expiry
```